version: '3'

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 4000:3000
    environment:
      SERVER: mongodb+srv://user:user@TarannumMongoDB.uf3qxwq.mongodb.net/notes?retryWrites=true&w=majority
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
